# Generated by Django 5.2.14 on 2026-05-24 17:39

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='fehca_creacion',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='orden',
            name='numero_orden',
            field=models.CharField(default=orders.models.Orden.generar_numero_orden, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_repartidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
