# Generated by Django 5.2.14 on 2026-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_fehca_creacion_orden_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
