# Generated by Django 5.2.14 on 2026-05-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_detalleorden_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='ESTADOS_PAGO',
            new_name='estado_pago',
        ),
    ]
